name: Deploy to GH pages

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Install dependencies
        run: npm ci
      - name: Build for GitHub Pages
        run: BASE_PATH=/escribania npm run build
      - name: GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          keep_history: true
          build_dir: ./build
          jekyll: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Build for dist (without base path)
        run: npm run build
      - name: Publish to dist branch
        uses: crazy-max/ghaction-github-pages@v2
        with:
          keep_history: true
          build_dir: ./build
          target_branch: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
